[2023-10-15T15:11:57.307+0100] {processor.py:153} INFO - Started process (PID=29471) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:11:57.309+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:11:57.309+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:11:57.309+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:11:57.324+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:11:57.323+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:11:57.324+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:11:57.324+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:11:57.324+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:11:57.466+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2023-10-15T15:13:07.366+0100] {processor.py:153} INFO - Started process (PID=29823) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:13:07.369+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:13:07.369+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:13:07.369+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:13:07.389+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:13:07.389+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:13:07.389+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:13:07.389+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:13:07.389+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:13:07.552+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2023-10-15T15:14:10.999+0100] {processor.py:153} INFO - Started process (PID=30162) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:14:11.001+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:14:11.002+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:14:11.002+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:14:11.016+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:14:11.015+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:14:11.016+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:14:11.016+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:14:11.016+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:14:11.163+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.164 seconds
[2023-10-15T15:15:15.329+0100] {processor.py:153} INFO - Started process (PID=30309) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:15:15.332+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:15:15.332+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:15:15.332+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:15:15.346+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:15:15.346+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:15:15.346+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:15:15.346+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:15:15.346+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:15:15.485+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.156 seconds
[2023-10-15T15:20:39.533+0100] {processor.py:153} INFO - Started process (PID=30921) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:20:39.535+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:20:39.535+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:20:39.535+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:20:39.550+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:20:39.550+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:20:39.550+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:20:39.550+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:20:39.550+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:20:39.705+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.172 seconds
[2023-10-15T15:21:47.610+0100] {processor.py:153} INFO - Started process (PID=31140) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:21:47.612+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:21:47.612+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:21:47.612+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:21:47.626+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:21:47.626+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:21:47.627+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:21:47.626+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:21:47.627+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:21:47.765+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2023-10-15T15:22:50.070+0100] {processor.py:153} INFO - Started process (PID=31284) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:22:50.073+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:22:50.073+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:22:50.073+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:22:50.092+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:22:50.092+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:22:50.093+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:22:50.093+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:22:50.093+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:22:50.254+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.184 seconds
[2023-10-15T15:23:55.905+0100] {processor.py:153} INFO - Started process (PID=31426) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:23:55.907+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:23:55.908+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:23:55.908+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:23:55.922+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:23:55.922+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:23:55.922+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:23:55.922+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:23:55.922+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:23:56.067+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.163 seconds
[2023-10-15T15:24:59.759+0100] {processor.py:153} INFO - Started process (PID=31560) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:24:59.761+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:24:59.761+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:24:59.761+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:24:59.774+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:24:59.774+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:24:59.774+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:24:59.774+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:24:59.775+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:24:59.943+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.185 seconds
[2023-10-15T15:26:04.876+0100] {processor.py:153} INFO - Started process (PID=31688) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:26:04.878+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:26:04.878+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:26:04.878+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:26:04.893+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:26:04.893+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:26:04.893+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:26:04.893+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:26:04.893+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:26:05.041+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2023-10-15T15:27:09.391+0100] {processor.py:153} INFO - Started process (PID=31800) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:27:09.393+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:27:09.393+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:27:09.393+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:27:09.407+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:27:09.407+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:27:09.407+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:27:09.407+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:27:09.407+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:27:09.549+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2023-10-15T15:28:12.003+0100] {processor.py:153} INFO - Started process (PID=31906) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:28:12.005+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:28:12.006+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:28:12.006+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:28:12.020+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:28:12.020+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:28:12.021+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:28:12.021+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:28:12.021+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:28:12.185+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2023-10-15T15:29:17.136+0100] {processor.py:153} INFO - Started process (PID=32025) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:29:17.138+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:29:17.138+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:29:17.138+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:29:17.154+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:29:17.154+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:29:17.155+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:29:17.155+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:29:17.155+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:29:17.331+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.196 seconds
[2023-10-15T15:30:21.194+0100] {processor.py:153} INFO - Started process (PID=32152) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:30:21.197+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:30:21.197+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:30:21.197+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:30:21.213+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:30:21.212+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:30:21.213+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:30:21.213+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:30:21.213+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:30:21.385+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.191 seconds
[2023-10-15T15:31:31.329+0100] {processor.py:153} INFO - Started process (PID=32279) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:31:31.332+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:31:31.332+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:31:31.332+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:31:31.347+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:31:31.347+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:31:31.347+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:31:31.347+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:31:31.347+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:31:31.500+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.171 seconds
[2023-10-15T15:32:35.973+0100] {processor.py:153} INFO - Started process (PID=32399) to work on /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:32:35.975+0100] {processor.py:743} INFO - Processing file /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-10-15T15:32:35.975+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:32:35.975+0100] {dagbag.py:532} INFO - Filling up the DagBag from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:32:35.990+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:32:35.989+0100] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-10-15T15:32:35.990+0100] {logging_mixin.py:137} INFO - [2023-10-15T15:32:35.990+0100] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-10-15T15:32:35.990+0100] {processor.py:755} WARNING - No viable dags retrieved from /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-10-15T15:32:36.139+0100] {processor.py:175} INFO - Processing /Users/b/Documents/workflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
