[2023-10-15T16:21:01.577+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute.taskB manual__2023-10-15T15:20:58.484008+00:00 [queued]>
[2023-10-15T16:21:01.580+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute.taskB manual__2023-10-15T15:20:58.484008+00:00 [queued]>
[2023-10-15T16:21:01.580+0100] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T16:21:01.580+0100] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-10-15T16:21:01.580+0100] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T16:21:01.583+0100] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): taskB> on 2023-10-15 15:20:58.484008+00:00
[2023-10-15T16:21:01.584+0100] {standard_task_runner.py:55} INFO - Started process 40698 to run task
[2023-10-15T16:21:01.587+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute', 'taskB', 'manual__2023-10-15T15:20:58.484008+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/execute.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmps1zw81vo']
[2023-10-15T16:21:01.588+0100] {standard_task_runner.py:83} INFO - Job 18: Subtask taskB
[2023-10-15T16:21:01.604+0100] {task_command.py:389} INFO - Running <TaskInstance: execute.taskB manual__2023-10-15T15:20:58.484008+00:00 [running]> on host 192.168.1.112
[2023-10-15T16:21:01.619+0100] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=workflow
AIRFLOW_CTX_DAG_ID=execute
AIRFLOW_CTX_TASK_ID=taskB
AIRFLOW_CTX_EXECUTION_DATE=2023-10-15T15:20:58.484008+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-15T15:20:58.484008+00:00
[2023-10-15T16:21:01.620+0100] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T
[2023-10-15T16:21:01.620+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n            echo taskB has been executed\n            slep 5\n            echo TASK B completed\n        \n        ']
[2023-10-15T16:21:01.625+0100] {subprocess.py:86} INFO - Output:
[2023-10-15T16:21:01.626+0100] {subprocess.py:93} INFO - taskB has been executed
[2023-10-15T16:21:01.629+0100] {subprocess.py:93} INFO - /bin/bash: line 2: slep: command not found
[2023-10-15T16:21:01.630+0100] {subprocess.py:93} INFO - TASK B completed
[2023-10-15T16:21:01.630+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-15T16:21:01.636+0100] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=execute, task_id=taskB, execution_date=20231015T152058, start_date=20231015T152101, end_date=20231015T152101
[2023-10-15T16:21:01.649+0100] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-10-15T16:21:01.655+0100] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
