[2023-10-16T15:12:21.219+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T14:12:16.465551+00:00 [queued]>
[2023-10-16T15:12:21.222+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T14:12:16.465551+00:00 [queued]>
[2023-10-16T15:12:21.222+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-16T15:12:21.226+0100] {taskinstance.py:1382} INFO - Executing <Task(SqliteOperator): insert_data2> on 2023-10-16 14:12:16.465551+00:00
[2023-10-16T15:12:21.228+0100] {standard_task_runner.py:57} INFO - Started process 99017 to run task
[2023-10-16T15:12:21.230+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_sqlite_pipeline', 'insert_data2', 'manual__2023-10-16T14:12:16.465551+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_pipeline.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpnum2tjoc']
[2023-10-16T15:12:21.232+0100] {standard_task_runner.py:85} INFO - Job 95: Subtask insert_data2
[2023-10-16T15:12:21.246+0100] {task_command.py:416} INFO - Running <TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T14:12:16.465551+00:00 [running]> on host 192.168.1.112
[2023-10-16T15:12:21.266+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='execute_sqlite_pipeline' AIRFLOW_CTX_TASK_ID='insert_data2' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T14:12:16.465551+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-16T14:12:16.465551+00:00'
[2023-10-16T15:12:21.266+0100] {sql.py:274} INFO - Executing: 
            INSERT INTO new_users (name, age) VALUES
                ('Seun', 23),
                ('Ali', 25),
                ('Tunde', 27),
                ('Muna', 21);
        
[2023-10-16T15:12:21.268+0100] {base.py:73} INFO - Using connection ID 'db_sqlite_conn' for task execution.
[2023-10-16T15:12:21.302+0100] {base.py:73} INFO - Using connection ID 'db_sqlite_conn' for task execution.
[2023-10-16T15:12:21.302+0100] {sql.py:418} INFO - Running statement: 
            INSERT INTO new_users (name, age) VALUES
                ('Seun', 23),
                ('Ali', 25),
                ('Tunde', 27),
                ('Muna', 21);
        , parameters: None
[2023-10-16T15:12:21.302+0100] {sql.py:427} INFO - Rows affected: 4
[2023-10-16T15:12:21.305+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=execute_sqlite_pipeline, task_id=insert_data2, execution_date=20231016T141216, start_date=20231016T141221, end_date=20231016T141221
[2023-10-16T15:12:21.337+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T15:12:21.346+0100] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
