[2023-10-16T16:07:26.011+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branch_exe.determine_branch scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T16:07:26.013+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branch_exe.determine_branch scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T16:07:26.013+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-16T16:07:26.017+0100] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): determine_branch> on 2023-10-15 00:00:00+00:00
[2023-10-16T16:07:26.019+0100] {standard_task_runner.py:57} INFO - Started process 6678 to run task
[2023-10-16T16:07:26.025+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'branch_exe', 'determine_branch', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/branch_exe.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmp1plk_sxe']
[2023-10-16T16:07:26.027+0100] {standard_task_runner.py:85} INFO - Job 110: Subtask determine_branch
[2023-10-16T16:07:26.050+0100] {task_command.py:416} INFO - Running <TaskInstance: branch_exe.determine_branch scheduled__2023-10-15T00:00:00+00:00 [running]> on host 192.168.1.112
[2023-10-16T16:07:26.069+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='branch_exe' AIRFLOW_CTX_TASK_ID='determine_branch' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-10-16T16:07:26.081+0100] {python.py:194} INFO - Done. Returned value was: filter_by_southwest
[2023-10-16T16:07:26.082+0100] {python.py:227} INFO - Branch callable return filter_by_southwest
[2023-10-16T16:07:26.082+0100] {skipmixin.py:173} INFO - Following branch filter_by_southwest
[2023-10-16T16:07:26.084+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 228, in execute
    self.skip_all_except(context["ti"], branch)
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/models/skipmixin.py", line 208, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filter_by_southwest'}.
[2023-10-16T16:07:26.086+0100] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=branch_exe, task_id=determine_branch, execution_date=20231015T000000, start_date=20231016T150726, end_date=20231016T150726
[2023-10-16T16:07:26.088+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task determine_branch ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'filter_by_southwest'}.; 6678)
[2023-10-16T16:07:26.129+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-16T16:07:26.142+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
