[2023-10-16T17:31:41.897+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup.taskChooseBranch scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-16T17:31:41.899+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup.taskChooseBranch scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-16T17:31:41.899+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-16T17:31:41.903+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): taskChooseBranch> on 2023-10-07 00:00:00+00:00
[2023-10-16T17:31:41.904+0100] {standard_task_runner.py:57} INFO - Started process 18388 to run task
[2023-10-16T17:31:41.907+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'cron_catchup', 'taskChooseBranch', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/catchup.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmp8_qj9hh3']
[2023-10-16T17:31:41.908+0100] {standard_task_runner.py:85} INFO - Job 179: Subtask taskChooseBranch
[2023-10-16T17:31:41.923+0100] {task_command.py:416} INFO - Running <TaskInstance: cron_catchup.taskChooseBranch scheduled__2023-10-07T00:00:00+00:00 [running]> on host 192.168.1.112
[2023-10-16T17:31:41.942+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='cron_catchup' AIRFLOW_CTX_TASK_ID='taskChooseBranch' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2023-10-16T17:31:41.942+0100] {python.py:194} INFO - Done. Returned value was: False
[2023-10-16T17:31:41.950+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=cron_catchup, task_id=taskChooseBranch, execution_date=20231007T000000, start_date=20231016T163141, end_date=20231016T163141
[2023-10-16T17:31:41.969+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T17:31:41.977+0100] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
